[features]
seeds = false

[programs.localnet]
fighter_generator = "JAdBaeRXnML6nVBAUuFXPGpH954PpCB4oX9oGS4bU8Hw"
stadium = "4xJYx25MR592rcJ3YDydsDXtuDa1mheyDAbeu9MLfkw3"

[programs.devnet]
fighter_generator = "JAdBaeRXnML6nVBAUuFXPGpH954PpCB4oX9oGS4bU8Hw"
stadium = "4xJYx25MR592rcJ3YDydsDXtuDa1mheyDAbeu9MLfkw3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/root/pls.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
