[features]
seeds = false

[programs.localnet]
battlefield = "Aiq2rRdx2fDXtPk2jUMy9gzpYr6hf2W9C7wbHkt2z44A"

[programs.devnet]
battlefield = "Aiq2rRdx2fDXtPk2jUMy9gzpYr6hf2W9C7wbHkt2z44A"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/c/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
